services:
  character-recognition:
    build: ./character-recognition
    container_name: character-recognition
    ports:
      - "5001:5001"
    volumes:
      - ./character-recognition:/app
    networks:
      - app-network

  paraphrasing-tool:
    build: ./paraphrasing-tool
    container_name: paraphraser
    ports:
      - "5002:5000"
    volumes:
      - ./paraphrasing-tool:/app
    networks:
      - app-network

  voice-transcription:
    build: ./voice-transcription
    container_name: voice-transcription
    ports:
      - "8000:8000"
    networks:
      - app-network

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    ports:
      - "5555:5554"
    networks:
      - app-network

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:80"
    networks:
      - app-network

  user-management:
    container_name: user-management
    build: ./user-management
    ports:
      - "5000:5000"
    networks:
      - app-network      

  summarizing-tool:
    container_name: summarizing-tool
    build: ./summarizing-tool/fastapi
    ports:
      - 8001:8001
    # volumes: # not needed
    #   - ./fastapi:/app
    networks:
      - app-network
  
  ollama:
    container_name: ollama
    build: ./summarizing-tool/ollama
    ports:
      - 11434:11434
    volumes:
      - app-volume:/ollama
    networks:
      - app-network
    entrypoint: ["/usr/bin/bash", "/pull-llama3.sh"]

networks:
  app-network:
    driver: bridge

volumes:
  app-volume:
    driver: local