services:
  character-recognition:
    build: ./character-recognition
    ports:
      - "5001:5001"
    volumes:
      - ./character-recognition:/app
    networks:
      - app-network

  paraphrasing-tool:
    build: ./paraphrasing-tool
    ports:
      - "5002:5000"
    volumes:
      - ./paraphrasing-tool:/app
    networks:
      - app-network

  voice-transcription:
    build: ./voice-transcription  # This ensures the build context is set correctly
    ports:
      - "5003:8000"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge