services:
  character-recognition:
    build: ./character-recognition
    ports:
      - "5001:5001"
    volumes:
      - ./character-recognition:/app
    networks:
      - app-network

  paraphrasing-tool:
    build: ./paraphrasing-tool
    ports:
      - "5002:5000"
    volumes:
      - ./paraphrasing-tool:/app
    networks:
      - app-network

  voice-transcription:
    build: ./voice-transcription
    container_name: voice-transcription
    ports:
      - "5003:8000"
    networks:
      - app-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "5555:5554"
    networks:
      - app-network

  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map port 80 of the container to port 3000 on the host
    networks:
      - app-network

networks:
  app-network:
    driver: bridge