services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=production
    volumes:
      - .:/app
    depends_on:
      - prometheus
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5001/health" ]
      interval: 30s
      retries: 3

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locustfile.py:/mnt/locust/locustfile.py
      - ./tests:/mnt/locust/tests
    environment:
      TARGET_HOST: http://app:5001
    depends_on:
      - app
    command: >
      -f /mnt/locust/locustfile.py --host=http://app:5001