global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['app:5001']

  - job_name: 'locust'
    static_configs:
      - targets: ['locust:8090']