name: Optical character recognition Service CI

on:
  push:
    paths:
      - 'character-recognition/**'
  pull_request:
    paths:
      - 'character-recognition/**'

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t character-recognition ./character-recognition

      - name: Run Tests
        run: |
          docker run --rm character-recognition bash -c "poetry run pytest tests"
