name: Optical Character Recognition Service CI

on:
  push:
    paths:
      - 'character-recognition/**'
  pull_request:
    paths:
      - 'character-recognition/**'

jobs:
  lint-format-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: docker build -t character-recognition ./character-recognition

      - name: Run Tests
        run: |
          docker run --rm character-recognition bash -c "poetry run pytest tests"

  performance-test:
    runs-on: ubuntu-latest
    needs: lint-format-test

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Start Application Using Docker Compose
        run: docker compose -f ./character-recognition/docker-compose.yml up -d

      - name: Run Performance Tests (Locust)
        working-directory: ./character-recognition
        run: |
          docker compose exec locust locust --host=http://app:5001 --headless --users 10 --spawn-rate 1 -t 5m --csv=locust_results

      - name: Upload Performance Test Results as Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: locust-results
          path: ./character-recognition/locust_results*

      - name: Tear Down Docker Containers
        if: always()
        run: docker compose down